### ISSUE TITLE
Use label fields properly

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-kitsu#13]
When an entity with unsupported characters is synced to ayon, characters are just stripped/replaced with underscores. 
We should store the original kitsu name in a label fileld.

**Comment by BigRoy** [comment]
[Cross-referencing this discussion on Discord](https://discord.com/channels/517362899170230292/1196476348579975329/1196486806397538544) that mentions the syncing currently skips invalid names completely and not just "strips/replaces" invalid characters.

Not sure why the sync behavior described there differs from what this issue describes.

**Comment by MadsHangaard** [comment]
> [Cross-referencing this discussion on Discord](https://discord.com/channels/517362899170230292/1196476348579975329/1196486806397538544) that mentions the syncing currently skips invalid names completely and not just "strips/replaces" invalid characters.
> 
> Not sure why the sync behavior described there differs from what this issue describes.

Yes, I've just made another attempt. Creating an asset with a space in the name doesn't sync for me.

**Comment by fabiaserra** [comment]
I'm experiencing the same with the SG syncer where shots named like `_2d_shot` are synced as `2d_shot`
