### ISSUE TITLE
Kitsu Listeners

### ISSUE THREAD

**Issue by scottmcdonnell** [ynput/ayon-kitsu#17]
From looking at the code the current addon does a full sync with a kitsu project and is fired by a button press in the Ayon front end.  In Openpype there was the [syncservice](https://github.com/ynput/OpenPype/blob/develop/openpype/modules/kitsu/utils/sync_service.py) which used Gazu to listen to Kitsu events and sync them with OpenPype database. The Ayon service seems ideal for this. Is the intention for this addon to sync on events in the future?

**Comment by EmberLightVFX** [comment]
I have started working on this and have gotten the listener into a working Ayon service. Next step is to sync the individual events with Ayon.
I'm currently waiting for https://github.com/ynput/ayon-kitsu/pull/18 to be merged as the new service is relying on that merge.

**Comment by scottmcdonnell** [comment]
If the kitsu listeners such as `asset:new` `episode:new` `task.new` etc and `asset:update` `episode:update` `task.update` etc POST the kitsu entities to the current endpoint `/addons/kitsu/{version}/push` push.py will handle create and update for kitsu entities. There will need to be a DELETE method added so that entities can be deleted too.

Also `project.update` will need to update the project anatomy so that will need an endpoint. Does `project.delete`  delete the project in Ayon?

I have made progress with the tests and have mocked much of the Kitsu data for testing the endpoints.  I will have a fork up shortly. 

> I have started working on this and have gotten the listener into a working Ayon service. Next step is to sync the individual events with Ayon. I'm currently waiting for #18 to be merged as the new service is relying on that merge.

Do you have any code up yet?
